# Generated by Django 4.2.7 on 2026-02-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_count", models.IntegerField()),
                ("avg_flowrate", models.FloatField()),
                ("avg_pressure", models.FloatField()),
                ("avg_temperature", models.FloatField()),
                ("type_distribution", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-upload_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Reactor", "Reactor"),
                            ("Pump", "Pump"),
                            ("Heat Exchanger", "Heat Exchanger"),
                            ("Compressor", "Compressor"),
                            ("Valve", "Valve"),
                        ],
                        max_length=100,
                    ),
                ),
                ("flowrate", models.FloatField()),
                ("pressure", models.FloatField()),
                ("temperature", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="equipment_api.datasetupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
